#!/usr/bin/env bash
PLUGIN_LIST="plug_list.vim"
sort -c $PLUGIN_LIST 2>/dev/null 1>/dev/null
if [ "$?" != "0" ]; then
	echo 'Sorting plug_list.vim ...'
	sort $PLUGIN_LIST -o $PLUGIN_LIST
	git reset HEAD $PLUGIN_LIST
	echo 'Please commit again!'
	exit 1
fi
